/**
 * rust/ の走査器を wasm32 でビルドし、src/wasm/scanner.gen.ts に base64 で埋める。
 *
 *   bun run build:wasm
 *
 * cargo が PATH に無ければ ~/.cargo/bin/cargo を使う (rustup を入れただけのシェル向け)。
 */

import { existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')
const crate = join(root, 'rust')
const target = 'wasm32-unknown-unknown'
const artifact = join(crate, 'target', target, 'release', 'tsshogi_detect_scan.wasm')
const output = join(root, 'src', 'wasm', 'scanner.gen.ts')

function cargo(): string {
  const fromPath = Bun.which('cargo')
  if (fromPath !== null) return fromPath
  const fallback = join(homedir(), '.cargo', 'bin', 'cargo')
  if (existsSync(fallback)) return fallback
  throw new Error('cargo was not found on PATH or in ~/.cargo/bin')
}

const bin = cargo()
// rustup の shim は同じディレクトリの rustc を探すので、PATH にも足しておく
const env = { ...process.env, PATH: `${join(bin, '..')}:${process.env.PATH ?? ''}` }
const build = Bun.spawnSync([bin, 'build', '--target', target, '--release'], {
  cwd: crate,
  env,
  stdout: 'inherit',
  stderr: 'inherit',
})
if (build.exitCode !== 0) {
  console.error(`cargo build failed with exit code ${build.exitCode}`)
  process.exit(build.exitCode ?? 1)
}

const bytes = new Uint8Array(await Bun.file(artifact).arrayBuffer())
const base64 = Buffer.from(bytes).toString('base64')
await Bun.write(
  output,
  [
    '// GENERATED by scripts/build-wasm.ts from rust/. Do not edit.',
    `// ${bytes.byteLength} bytes of ${target} WASM.`,
    `export const SCANNER_WASM_BASE64 =\n  '${base64}'`,
    '',
  ].join('\n'),
)
console.log(`wrote ${output} (${bytes.byteLength} bytes of WASM)`)
